int SCREEN_WIDTH = 1500;
int SCREEN_HEIGHT = 500;

int MAP_WIDTH = 750;
int MAP_HEIGHT = 500;

int MENU_HEIGHT = 40;
int DATAVIEW_WIDTH = SCREEN_WIDTH - MAP_WIDTH;
int DATAVIEW_HEIGHT = SCREEN_HEIGHT - MENU_HEIGHT;
