int SCREEN_WIDTH = 1500;
int SCREEN_HEIGHT = 500;

int MAP_OFFSET = -10;
int MAP_WIDTH = 700;
int MAP_EDGE = MAP_WIDTH + MAP_OFFSET;
int MAP_HEIGHT = 500;

int MENU_HEIGHT = 40;
int DATAVIEW_WIDTH = SCREEN_WIDTH - MAP_EDGE;
int DATAVIEW_HEIGHT = SCREEN_HEIGHT - MENU_HEIGHT;
